name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt

    ## Enter the GitHub Actions runner via SSH (the SSH address will be displayed in the action log) and view your secrets file.
    - name: Run tmate
     # uses: mxschmitt/action-tmate@v2  ## uncomment
